### ISSUE TITLE
Actividad 2 Infografía Vanessa cruz ortiz 1BS

### ISSUE THREAD

**Issue by Vanessacruzortiz** [SistemasTecTlaxiaco/actividad-2-infografia-Vanessacruzortiz#1]
![20220902_111536_0000](https://user-images.githubusercontent.com/112358449/188251319-688ba9b9-c3f5-407c-9f5a-a9b9d129d146.png)

**Comment by Vanessacruzortiz** [comment]
Actividad 2 Infografía
Vanessa Cruz Ortiz 1BS
![20220902_111333_0000](https://user-images.githubusercontent.com/112358449/188251291-fe01dcc2-ed99-4a8c-98e5-7cd7dec1c426.png)

**Comment by Daisy-GonzalezLita12** [comment]
18.4

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
